VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DbRecordsetFactory"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_Description = "An implementation of an abstract factory that creates DbRecordset objects."
'@Folder "SecureADODB.DbRecordset"
'@ModuleDescription "An implementation of an abstract factory that creates DbRecordset objects."
'@PredeclaredId
'@Exposed
Option Explicit
